linters-settings:
  custom:
    modreplace:
      # Path is required
      path: modreplace.so
      # Description is optional
      description: Check for replace directives in go.mod files.
      # Original-url is optional, and is only used for documentation purposes.
      original-url: github.com/pentops/golint-modfile-replace

linters:
  disable-all: true
  enable:
    - modreplace
    # Typecheck is how golangci-lint reports compile errors, so should always be enabled.
    - typecheck